package pr_ui;


import java.util.ArrayList;
import java.util.List;
import javax.swing.*;
import javafx.scene.control.ComboBox;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PR_Window.java
 *
 * Created on 2013-03-05, 19:40:56
 */
/**
 *
 * @author krzy
 */
public class PR_Window extends javax.swing.JFrame {

    /**
     * Creates new form PR_GUI
     */
    public PR_Window() {
        initComponents();
       

        setSize(800, 600);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbg_F = new javax.swing.ButtonGroup();
        JB_ReadDataSet = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        l_dataset_name_l = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        l_dataset_name = new javax.swing.JLabel();
        l_nfeatures = new javax.swing.JLabel();
        l_n_of_classes = new javax.swing.JLabel();
        JB_ParseDataSet = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        selbox_nfeat = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        f_rb_extr = new javax.swing.JRadioButton();
        f_rb_sel = new javax.swing.JRadioButton();
        b_deriveFS = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        f_combo_criterion = new javax.swing.JComboBox();
        f_combo_PCA_LDA = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        tf_PCA_Energy = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        l_NewDim = new javax.swing.JLabel();
        b_deriveFS1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        JCB_CalassiferType = new javax.swing.JComboBox();
        JB_Main_Train = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        tf_TrainSetSize = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        JB_Main_Exe = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        l_FLD_winner = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        l_FLD_val = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        JLab_FLD_looser_value = new javax.swing.JLabel();
        jLab_FLD_looser_indx = new javax.swing.JLabel();
        lab_classResult = new javax.swing.JLabel();
        l_FLD_val1 = new javax.swing.JLabel();
        jLab_FLD_looser_indx1 = new javax.swing.JLabel();
        JLab_FLD_looser_value1 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        kTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(800, 400));
        getContentPane().setLayout(null);

        JB_ReadDataSet.setText("Read dataset");
        getContentPane().add(JB_ReadDataSet);
        JB_ReadDataSet.setBounds(20, 10, 130, 25);

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel1.setText("Dataset info");

        l_dataset_name_l.setText("Name:");

        jLabel3.setText("Classes:");

        jLabel4.setText("Features:");

        l_dataset_name.setText("...");

        l_nfeatures.setText("...");

        l_n_of_classes.setText("...");
        l_n_of_classes.setName("l_n_of_classes"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(l_dataset_name_l)
                        .addGap(18, 18, 18)
                        .addComponent(l_dataset_name))
                    .addComponent(jLabel1))
                .addGap(94, 94, 94)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l_nfeatures, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(l_n_of_classes, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(61, 61, 61))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(l_n_of_classes))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_dataset_name_l)
                    .addComponent(jLabel4)
                    .addComponent(l_dataset_name)
                    .addComponent(l_nfeatures))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        l_n_of_classes.getAccessibleContext().setAccessibleName("l_n_of_classes");

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 40, 320, 70);

        JB_ParseDataSet.setText("Parse dataset");
        getContentPane().add(JB_ParseDataSet);
        JB_ParseDataSet.setBounds(190, 10, 130, 25);

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel5.setText("Feature space");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(14, 2, 118, 26);

        jLabel6.setText("FS Dimension");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(178, 9, 78, 16);

        selbox_nfeat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1" }));
        selbox_nfeat.setMinimumSize(new java.awt.Dimension(40, 20));
        selbox_nfeat.setPreferredSize(new java.awt.Dimension(40, 20));
        jPanel3.add(selbox_nfeat);
        selbox_nfeat.setBounds(259, 6, 50, 20);
        jPanel3.add(jSeparator1);
        jSeparator1.setBounds(14, 41, 290, 10);

        f_rb_extr.setBackground(new java.awt.Color(255, 255, 204));
        rbg_F.add(f_rb_extr);
        f_rb_extr.setText("Feature extraction");
        jPanel3.add(f_rb_extr);
        f_rb_extr.setBounds(10, 110, 133, 25);

        f_rb_sel.setBackground(new java.awt.Color(255, 255, 204));
        rbg_F.add(f_rb_sel);
        f_rb_sel.setSelected(true);
        f_rb_sel.setText("Feature selection");
        jPanel3.add(f_rb_sel);
        f_rb_sel.setBounds(10, 60, 127, 25);

        b_deriveFS.setText("Optimal Derive Feature Space");
        jPanel3.add(b_deriveFS);
        b_deriveFS.setBounds(10, 210, 292, 25);

        jLabel10.setText("Criterion");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(200, 50, 49, 16);

        f_combo_criterion.setEditable(true);
        f_combo_criterion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Fisher discriminant", "Classification error" }));
        jPanel3.add(f_combo_criterion);
        f_combo_criterion.setBounds(160, 70, 140, 22);

        f_combo_PCA_LDA.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PCA", "LDA" }));
        f_combo_PCA_LDA.setEnabled(false);
        jPanel3.add(f_combo_PCA_LDA);
        f_combo_PCA_LDA.setBounds(190, 110, 70, 22);

        jLabel12.setText("Energy");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(20, 150, 39, 16);

        tf_PCA_Energy.setText("80");
        jPanel3.add(tf_PCA_Energy);
        tf_PCA_Energy.setBounds(70, 150, 30, 22);

        jLabel14.setText("%");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(110, 150, 20, 16);

        jLabel15.setText("New dimension:");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(160, 150, 92, 16);

        l_NewDim.setText("...");
        jPanel3.add(l_NewDim);
        l_NewDim.setBounds(270, 150, 30, 16);

        b_deriveFS1.setText("Derive Feature Space");
        jPanel3.add(b_deriveFS1);
        b_deriveFS1.setBounds(10, 180, 292, 25);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(10, 110, 320, 250);

        jPanel4.setBackground(new java.awt.Color(204, 255, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel8.setText("Classifier");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(10, 0, 79, 26);

        jLabel9.setText("Method");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(14, 44, 42, 16);

        JCB_CalassiferType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nearest neighbor (NN)", "Nearest Mean (NM)", "k-Nearest Neighbor (k-NN)", "k-Nearest Mean (k-NM)" }));
        jPanel4.add(JCB_CalassiferType);
        JCB_CalassiferType.setBounds(74, 41, 178, 22);

        JB_Main_Train.setText("Train");
        jPanel4.add(JB_Main_Train);
        JB_Main_Train.setBounds(40, 130, 98, 25);

        jButton4.setText("Test Matrix/DoubleArr");
        jPanel4.add(jButton4);
        jButton4.setBounds(66, 90, 240, 30);

        jLabel16.setText("Training part:");
        jPanel4.add(jLabel16);
        jLabel16.setBounds(20, 170, 80, 16);

        tf_TrainSetSize.setText("80");
        jPanel4.add(tf_TrainSetSize);
        tf_TrainSetSize.setBounds(110, 170, 20, 22);

        jLabel17.setText("%");
        jPanel4.add(jLabel17);
        jLabel17.setBounds(140, 170, 20, 16);

        JB_Main_Exe.setText("Execute");
        jPanel4.add(JB_Main_Exe);
        JB_Main_Exe.setBounds(210, 130, 96, 25);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(610, 0, 350, 240);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Results"));
        jPanel5.setLayout(null);

        jLabel2.setText("FS Winner:");
        jPanel5.add(jLabel2);
        jLabel2.setBounds(10, 20, 70, 16);

        l_FLD_winner.setText("xxx");
        l_FLD_winner.setMaximumSize(new java.awt.Dimension(18, 230));
        l_FLD_winner.setMinimumSize(new java.awt.Dimension(18, 230));
        jPanel5.add(l_FLD_winner);
        l_FLD_winner.setBounds(100, 20, 140, 16);

        jLabel13.setText("FLD value: ");
        jPanel5.add(jLabel13);
        jLabel13.setBounds(10, 40, 70, 16);

        l_FLD_val.setText("vvv");
        l_FLD_val.setMaximumSize(new java.awt.Dimension(18, 230));
        l_FLD_val.setMinimumSize(new java.awt.Dimension(18, 230));
        jPanel5.add(l_FLD_val);
        l_FLD_val.setBounds(100, 40, 140, 16);

        jLabel7.setText("FS Looser:");
        jLabel7.setName("jLab_FS_Looser"); // NOI18N
        jPanel5.add(jLabel7);
        jLabel7.setBounds(10, 60, 70, 16);

        jLabel11.setText("FD value:");
        jLabel11.setName("jLab_FLD_Value"); // NOI18N
        jPanel5.add(jLabel11);
        jLabel11.setBounds(10, 80, 70, 16);

        JLab_FLD_looser_value.setText("vvv");
        JLab_FLD_looser_value.setMaximumSize(new java.awt.Dimension(18, 230));
        JLab_FLD_looser_value.setMinimumSize(new java.awt.Dimension(18, 230));
        jPanel5.add(JLab_FLD_looser_value);
        JLab_FLD_looser_value.setBounds(100, 80, 140, 16);

        jLab_FLD_looser_indx.setText("vvv");
        jLab_FLD_looser_indx.setMaximumSize(new java.awt.Dimension(18, 230));
        jLab_FLD_looser_indx.setMinimumSize(new java.awt.Dimension(18, 230));
        jPanel5.add(jLab_FLD_looser_indx);
        jLab_FLD_looser_indx.setBounds(100, 60, 140, 16);

        lab_classResult.setText("xxx");
        lab_classResult.setMaximumSize(new java.awt.Dimension(18, 230));
        lab_classResult.setMinimumSize(new java.awt.Dimension(18, 230));
        jPanel5.add(lab_classResult);
        lab_classResult.setBounds(100, 110, 140, 16);

        l_FLD_val1.setText("vvv");
        l_FLD_val1.setMaximumSize(new java.awt.Dimension(18, 230));
        l_FLD_val1.setMinimumSize(new java.awt.Dimension(18, 230));
        jPanel5.add(l_FLD_val1);
        l_FLD_val1.setBounds(100, 130, 140, 16);

        jLab_FLD_looser_indx1.setText("vvv");
        jLab_FLD_looser_indx1.setMaximumSize(new java.awt.Dimension(18, 230));
        jLab_FLD_looser_indx1.setMinimumSize(new java.awt.Dimension(18, 230));
        jPanel5.add(jLab_FLD_looser_indx1);
        jLab_FLD_looser_indx1.setBounds(100, 150, 140, 16);

        JLab_FLD_looser_value1.setText("vvv");
        JLab_FLD_looser_value1.setMaximumSize(new java.awt.Dimension(18, 230));
        JLab_FLD_looser_value1.setMinimumSize(new java.awt.Dimension(18, 230));
        jPanel5.add(JLab_FLD_looser_value1);
        JLab_FLD_looser_value1.setBounds(100, 170, 140, 16);

        jLabel18.setText("Class Res.");
        jLabel18.setName(""); // NOI18N
        jPanel5.add(jLabel18);
        jLabel18.setBounds(10, 110, 70, 16);

        jLabel19.setText("FD value:");
        jLabel19.setName("jLab_FLD_Value"); // NOI18N
        jPanel5.add(jLabel19);
        jLabel19.setBounds(10, 170, 70, 16);

        jLabel20.setText("FLD value: ");
        jPanel5.add(jLabel20);
        jLabel20.setBounds(10, 130, 70, 16);

        jLabel21.setText("FS Looser:");
        jLabel21.setName("jLab_FS_Looser"); // NOI18N
        jPanel5.add(jLabel21);
        jLabel21.setBounds(10, 150, 70, 16);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(340, 0, 260, 360);
        getContentPane().add(kTextField);
        kTextField.setBounds(610, 250, 230, 110);

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton JB_Main_Exe;
    protected javax.swing.JButton JB_Main_Train;
    protected javax.swing.JButton JB_ParseDataSet;
    protected javax.swing.JButton JB_ReadDataSet;
    protected javax.swing.JComboBox JCB_CalassiferType;
    protected javax.swing.JLabel JLab_FLD_looser_value;
    protected javax.swing.JLabel JLab_FLD_looser_value1;
    protected javax.swing.JButton b_deriveFS;
    protected javax.swing.JButton b_deriveFS1;
    protected javax.swing.JComboBox f_combo_PCA_LDA;
    protected javax.swing.JComboBox f_combo_criterion;
    protected javax.swing.JRadioButton f_rb_extr;
    protected javax.swing.JRadioButton f_rb_sel;
    protected javax.swing.JButton jButton4;
    protected javax.swing.JLabel jLab_FLD_looser_indx;
    protected javax.swing.JLabel jLab_FLD_looser_indx1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    protected javax.swing.JLabel jLabel18;
    protected javax.swing.JLabel jLabel19;
    protected javax.swing.JLabel jLabel2;
    protected javax.swing.JLabel jLabel20;
    protected javax.swing.JLabel jLabel21;
    protected javax.swing.JLabel jLabel3;
    protected javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    protected javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    protected javax.swing.JTextField kTextField;
    protected javax.swing.JLabel l_FLD_val;
    protected javax.swing.JLabel l_FLD_val1;
    protected javax.swing.JLabel l_FLD_winner;
    protected javax.swing.JLabel l_NewDim;
    protected javax.swing.JLabel l_dataset_name;
    private javax.swing.JLabel l_dataset_name_l;
    protected javax.swing.JLabel l_n_of_classes;
    protected javax.swing.JLabel l_nfeatures;
    protected javax.swing.JLabel lab_classResult;
    private javax.swing.ButtonGroup rbg_F;
    protected javax.swing.JComboBox selbox_nfeat;
    protected javax.swing.JTextField tf_PCA_Energy;
    protected javax.swing.JTextField tf_TrainSetSize;
    // End of variables declaration//GEN-END:variables
	
   
    }
